"""add prevention_actions table

Revision ID: 0cf1e41c6d30
Revises: 28fd64309a40
Create Date: 2026-08-19 08:06:42.108621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf1e41c6d30'
down_revision: Union[str, Sequence[str], None] = '28fd64309a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prevention_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('requested_action', sa.String(length=32), nullable=False),
    sa.Column('actual_action', sa.String(length=32), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=False),
    sa.Column('target_scope', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prevention_actions_actual_action'), 'prevention_actions', ['actual_action'], unique=False)
    op.create_index(op.f('ix_prevention_actions_created_at'), 'prevention_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prevention_actions_event_id'), 'prevention_actions', ['event_id'], unique=False)
    op.create_index(op.f('ix_prevention_actions_requested_action'), 'prevention_actions', ['requested_action'], unique=False)
    op.create_index(op.f('ix_prevention_actions_source_ip'), 'prevention_actions', ['source_ip'], unique=False)
    op.create_index(op.f('ix_prevention_actions_success'), 'prevention_actions', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prevention_actions_success'), table_name='prevention_actions')
    op.drop_index(op.f('ix_prevention_actions_source_ip'), table_name='prevention_actions')
    op.drop_index(op.f('ix_prevention_actions_requested_action'), table_name='prevention_actions')
    op.drop_index(op.f('ix_prevention_actions_event_id'), table_name='prevention_actions')
    op.drop_index(op.f('ix_prevention_actions_created_at'), table_name='prevention_actions')
    op.drop_index(op.f('ix_prevention_actions_actual_action'), table_name='prevention_actions')
    op.drop_table('prevention_actions')
    # ### end Alembic commands ###
