"""initial schema

Revision ID: 28fd64309a40
Revises: 
Create Date: 2026-08-18 10:21:12.741047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fd64309a40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_uid', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_ip', sa.String(length=64), nullable=False),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.Integer(), nullable=True),
    sa.Column('canonical_attack_label', sa.String(length=64), nullable=True),
    sa.Column('traffic_class', sa.String(length=16), nullable=True),
    sa.Column('source', sa.Enum('OFFLINE_DEMO', 'TEST_EVENT', 'LIVE', name='eventsource'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_destination_ip'), 'events', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_events_event_uid'), 'events', ['event_uid'], unique=True)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index(op.f('ix_events_source_ip'), 'events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_component'), 'model_versions', ['component'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attack_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=False),
    sa.Column('dst_ip', sa.String(length=64), nullable=False),
    sa.Column('flow_count', sa.Integer(), nullable=False),
    sa.Column('benign_flow_count', sa.Integer(), nullable=False),
    sa.Column('attack_flow_count', sa.Integer(), nullable=False),
    sa.Column('attack_ratio', sa.Float(), nullable=False),
    sa.Column('unique_source_ports', sa.Integer(), nullable=False),
    sa.Column('unique_destination_ports', sa.Integer(), nullable=False),
    sa.Column('protocols_seen', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('total_forward_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_backward_bytes', sa.BigInteger(), nullable=False),
    sa.Column('attack_labels', sa.JSON(), nullable=False),
    sa.Column('graph_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_ip', 'dst_ip', 'graph_version_id', name='uq_attack_edge_pair_version')
    )
    op.create_index(op.f('ix_attack_edges_attack_flow_count'), 'attack_edges', ['attack_flow_count'], unique=False)
    op.create_index(op.f('ix_attack_edges_attack_ratio'), 'attack_edges', ['attack_ratio'], unique=False)
    op.create_index(op.f('ix_attack_edges_dst_ip'), 'attack_edges', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_attack_edges_graph_version_id'), 'attack_edges', ['graph_version_id'], unique=False)
    op.create_index(op.f('ix_attack_edges_src_ip'), 'attack_edges', ['src_ip'], unique=False)
    op.create_table('attack_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('total_flow_count', sa.Integer(), nullable=False),
    sa.Column('benign_flow_count', sa.Integer(), nullable=False),
    sa.Column('attack_flow_count', sa.Integer(), nullable=False),
    sa.Column('attack_ratio', sa.Float(), nullable=False),
    sa.Column('in_degree', sa.Integer(), nullable=False),
    sa.Column('out_degree', sa.Integer(), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('graph_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'graph_version_id', name='uq_attack_node_ip_version')
    )
    op.create_index(op.f('ix_attack_nodes_attack_flow_count'), 'attack_nodes', ['attack_flow_count'], unique=False)
    op.create_index(op.f('ix_attack_nodes_degree'), 'attack_nodes', ['degree'], unique=False)
    op.create_index(op.f('ix_attack_nodes_graph_version_id'), 'attack_nodes', ['graph_version_id'], unique=False)
    op.create_index(op.f('ix_attack_nodes_ip'), 'attack_nodes', ['ip'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('reconstruction_error', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_event_id'), 'detections', ['event_id'], unique=True)
    op.create_index(op.f('ix_detections_is_anomaly'), 'detections', ['is_anomaly'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_category'), 'system_logs', ['category'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('rules_applied', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_config_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_config_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_created_at'), 'risk_assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_event_id'), 'risk_assessments', ['event_id'], unique=True)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_score'), 'risk_assessments', ['risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_risk_score'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_event_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_created_at'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_category'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_detections_is_anomaly'), table_name='detections')
    op.drop_index(op.f('ix_detections_event_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_attack_nodes_ip'), table_name='attack_nodes')
    op.drop_index(op.f('ix_attack_nodes_graph_version_id'), table_name='attack_nodes')
    op.drop_index(op.f('ix_attack_nodes_degree'), table_name='attack_nodes')
    op.drop_index(op.f('ix_attack_nodes_attack_flow_count'), table_name='attack_nodes')
    op.drop_table('attack_nodes')
    op.drop_index(op.f('ix_attack_edges_src_ip'), table_name='attack_edges')
    op.drop_index(op.f('ix_attack_edges_graph_version_id'), table_name='attack_edges')
    op.drop_index(op.f('ix_attack_edges_dst_ip'), table_name='attack_edges')
    op.drop_index(op.f('ix_attack_edges_attack_ratio'), table_name='attack_edges')
    op.drop_index(op.f('ix_attack_edges_attack_flow_count'), table_name='attack_edges')
    op.drop_table('attack_edges')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_versions_component'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_source_ip'), table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_event_uid'), table_name='events')
    op.drop_index(op.f('ix_events_destination_ip'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
